<?php
/**
 * Script para exibir a estrutura de diretórios em formato de árvore vertical
 * similar ao comando 'tree' em sistemas Linux/Windows
 */

// Função recursiva para exibir a estrutura de diretórios
function exibirEstrutura($diretorio, $prefixo = '')
{
    // Verifica se o diretório existe
    if (!is_dir($diretorio)) {
        echo "O diretório $diretorio não existe!";
        return;
    }

    // Verifica se o diretório atual é node_modules
    $dirName = basename($diretorio);
    if ($dirName === 'ios') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === 'android') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === 'linux') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === 'macos') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === 'test') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === 'web') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === 'windows') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === 'build') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === '.dart_tool') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }
    if ($dirName === '.idea') {
        // Apenas mostra o diretório node_modules, mas não seu conteúdo
        return;
    }

    // Lista os arquivos e pastas do diretório
    $itens = scandir($diretorio);

    // Array para armazenar diretórios e arquivos separadamente
    $diretorios = [];
    $arquivos = [];

    // Separa diretórios e arquivos
    foreach ($itens as $item) {
        if ($item != '.' && $item != '..') {
            $caminho = $diretorio . '/' . $item;
            if (is_dir($caminho)) {
                $diretorios[] = $item;
            } else {
                $arquivos[] = $item;
            }
        }
    }

    // Ordena os arrays
    sort($diretorios);
    sort($arquivos);

    // Combina os arrays, diretórios primeiro
    $todos = array_merge($diretorios, $arquivos);

    // Número total de itens
    $total = count($todos);

    // Para cada item
    for ($i = 0; $i < $total; $i++) {
        $item = $todos[$i];
        $caminho = $diretorio . '/' . $item;
        $isUltimo = ($i == $total - 1);

        // Exibe o item atual
        echo $prefixo . ($isUltimo ? "└── " : "├── ");

        if (is_dir($caminho)) {
            echo $item . "\\" . PHP_EOL;

            // Prefixo para os itens do próximo nível
            $novoPrefixo = $prefixo . ($isUltimo ? "    " : "│   ");

            // Chama recursivamente para o subdiretório
            exibirEstrutura($caminho, $novoPrefixo);
        } else {
            $extensao = pathinfo($item, PATHINFO_EXTENSION);
            echo $item . " (." . $extensao . ")" . PHP_EOL;
        }
    }
}

// Configura o tipo de conteúdo como texto plano
header('Content-Type: text/plain; charset=utf-8');

// Exibe o cabeçalho
echo "[FLUTTER]/" . PHP_EOL;
echo "│" . PHP_EOL;
echo "└── script\\" . PHP_EOL;

// Exibe a estrutura a partir do diretório 'script'
exibirEstrutura('../../flutter', "    ");

// Adiciona uma linha em branco entre as exibições
echo PHP_EOL;
// Adiciona uma linha em branco entre as exibições
echo PHP_EOL;
?>

<pre>

flutter pub deps
Dart SDK 3.7.2
Flutter SDK 3.29.3

modelo_v2 1.0.0+1
|-- audioplayers 6.4.0
|   |-- audioplayers_android 5.2.0
|   |   |-- audioplayers_platform_interface...
|   |   '-- flutter...
|   |-- audioplayers_darwin 6.2.0
|   |   |-- audioplayers_platform_interface...
|   |   '-- flutter...
|   |-- audioplayers_linux 4.2.0
|   |   |-- audioplayers_platform_interface...
|   |   '-- flutter...
|   |-- audioplayers_platform_interface 7.1.0
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- audioplayers_web 5.1.0
|   |   |-- audioplayers_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- web...
|   |-- audioplayers_windows 4.2.0
|   |   |-- audioplayers_platform_interface...
|   |   '-- flutter...
|   |-- file 7.0.1
|   |   |-- meta...
|   |   '-- path...
|   |-- path_provider 2.1.5
|   |   |-- path_provider_android 2.2.17
|   |   |   |-- flutter...
|   |   |   '-- path_provider_platform_interface...
|   |   |-- path_provider_foundation 2.4.1
|   |   |   |-- flutter...
|   |   |   '-- path_provider_platform_interface...
|   |   |-- path_provider_linux 2.2.1
|   |   |   |-- ffi 2.1.4
|   |   |   |-- xdg_directories 1.1.0
|   |   |   |   |-- meta...
|   |   |   |   '-- path...
|   |   |   |-- flutter...
|   |   |   |-- path...
|   |   |   '-- path_provider_platform_interface...
|   |   |-- path_provider_platform_interface 2.1.2
|   |   |   |-- platform 3.1.6
|   |   |   |-- flutter...
|   |   |   '-- plugin_platform_interface...
|   |   |-- path_provider_windows 2.3.0
|   |   |   |-- ffi...
|   |   |   |-- flutter...
|   |   |   |-- path...
|   |   |   '-- path_provider_platform_interface...
|   |   '-- flutter...
|   |-- synchronized 3.3.1
|   |-- uuid 4.5.1
|   |   |-- crypto 3.0.6
|   |   |   '-- typed_data...
|   |   |-- fixnum 1.1.1
|   |   |-- sprintf 7.0.0
|   |   '-- meta...
|   |-- flutter...
|   |-- http...
|   '-- meta...
|-- cupertino_icons 1.0.8
|-- flutter 0.0.0
|   |-- characters 1.4.0
|   |-- collection 1.19.1
|   |-- material_color_utilities 0.11.1
|   |   '-- collection...
|   |-- meta 1.16.0
|   |-- sky_engine 0.0.0
|   '-- vector_math 2.1.4
|-- flutter_lints 5.0.0
|   '-- lints 5.1.1
|-- flutter_map 8.1.1
|   |-- dart_earcut 1.2.0
|   |-- latlong2 0.9.1
|   |   '-- intl 0.20.2
|   |       |-- clock...
|   |       |-- meta...
|   |       '-- path...
|   |-- logger 2.5.0
|   |-- polylabel 1.0.1
|   |   '-- collection...
|   |-- proj4dart 2.1.0
|   |   |-- mgrs_dart 2.0.0
|   |   |   '-- unicode 0.3.1
|   |   |       '-- lists 1.0.1
|   |   |           '-- meta...
|   |   |-- wkt_parser 2.0.0
|   |   '-- meta...
|   |-- async...
|   |-- collection...
|   |-- flutter...
|   |-- http...
|   |-- meta...
|   '-- vector_math...
|-- flutter_stripe 11.5.0
|   |-- stripe_android 11.5.0
|   |   '-- flutter...
|   |-- stripe_ios 11.5.0
|   |   '-- flutter...
|   |-- stripe_platform_interface 11.5.0
|   |   |-- freezed_annotation 2.4.4
|   |   |   |-- collection...
|   |   |   |-- json_annotation...
|   |   |   '-- meta...
|   |   |-- json_annotation 4.9.0
|   |   |   '-- meta...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- flutter_test 0.0.0
|   |-- boolean_selector 2.1.2
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- clock 1.1.2
|   |-- fake_async 1.3.2
|   |   |-- clock...
|   |   '-- collection...
|   |-- leak_tracker 10.0.8
|   |   |-- clock...
|   |   |-- collection...
|   |   |-- meta...
|   |   |-- path...
|   |   '-- vm_service...
|   |-- leak_tracker_flutter_testing 3.0.9
|   |   |-- flutter...
|   |   |-- leak_tracker...
|   |   |-- leak_tracker_testing...
|   |   |-- matcher...
|   |   '-- meta...
|   |-- leak_tracker_testing 3.0.1
|   |   |-- leak_tracker...
|   |   |-- matcher...
|   |   '-- meta...
|   |-- matcher 0.12.17
|   |   |-- async...
|   |   |-- meta...
|   |   |-- stack_trace...
|   |   |-- term_glyph...
|   |   '-- test_api...
|   |-- path 1.9.1
|   |-- source_span 1.10.1
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.12.1
|   |   '-- path...
|   |-- stream_channel 2.1.4
|   |   '-- async...
|   |-- string_scanner 1.4.1
|   |   '-- source_span...
|   |-- term_glyph 1.2.2
|   |-- test_api 0.7.4
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- meta...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- vm_service 14.3.1
|   |-- async...
|   |-- characters...
|   |-- collection...
|   |-- flutter...
|   |-- material_color_utilities...
|   |-- meta...
|   '-- vector_math...
|-- geolocator 14.0.0
|   |-- geolocator_android 5.0.1+1
|   |   |-- flutter...
|   |   |-- geolocator_platform_interface...
|   |   |-- meta...
|   |   '-- uuid...
|   |-- geolocator_apple 2.3.13
|   |   |-- flutter...
|   |   '-- geolocator_platform_interface...
|   |-- geolocator_platform_interface 4.2.6
|   |   |-- plugin_platform_interface 2.1.8
|   |   |   '-- meta...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- vector_math...
|   |-- geolocator_web 4.1.3
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- geolocator_platform_interface...
|   |   '-- web...
|   |-- geolocator_windows 0.2.5
|   |   |-- flutter...
|   |   '-- geolocator_platform_interface...
|   '-- flutter...
|-- go_router 15.1.2
|   |-- flutter_web_plugins 0.0.0
|   |   |-- characters...
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- material_color_utilities...
|   |   |-- meta...
|   |   '-- vector_math...
|   |-- logging 1.3.0
|   |-- collection...
|   |-- flutter...
|   '-- meta...
|-- http 1.4.0
|   |-- async 2.12.0
|   |   |-- collection...
|   |   '-- meta...
|   |-- http_parser 4.1.2
|   |   |-- typed_data 1.4.0
|   |   |   '-- collection...
|   |   |-- collection...
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- web 1.1.1
|   '-- meta...
|-- permission_handler 12.0.0+1
|   |-- permission_handler_android 13.0.1
|   |   |-- flutter...
|   |   '-- permission_handler_platform_interface...
|   |-- permission_handler_apple 9.4.7
|   |   |-- flutter...
|   |   '-- permission_handler_platform_interface...
|   |-- permission_handler_html 0.1.3+5
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- permission_handler_platform_interface...
|   |   '-- web...
|   |-- permission_handler_platform_interface 4.3.0
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- permission_handler_windows 0.2.1
|   |   |-- flutter...
|   |   '-- permission_handler_platform_interface...
|   |-- flutter...
|   '-- meta...
'-- video_player 2.9.5
    |-- html 0.15.6
    |   |-- csslib 1.0.2
    |   |   '-- source_span...
    |   '-- source_span...
    |-- video_player_android 2.8.6
    |   |-- flutter...
    |   '-- video_player_platform_interface...
    |-- video_player_avfoundation 2.7.1
    |   |-- flutter...
    |   '-- video_player_platform_interface...
    |-- video_player_platform_interface 6.3.0
    |   |-- flutter...
    |   '-- plugin_platform_interface...
    |-- video_player_web 2.3.5
    |   |-- flutter...
    |   |-- flutter_web_plugins...
    |   |-- video_player_platform_interface...
    |   '-- web...
    '-- flutter...

</pre>